### ISSUE TITLE
Critical memory leak

### ISSUE THREAD

**Issue by duburcqa** [stack-of-tasks/eigenpy#156]
Hi,

There is a huge memory leak during the implicit conversion from numpy array to eigen matrix. Here is a script to reproduce the results on the attached figure.

```python
import numpy as np
import pinocchio as pnc

pnc_model = pnc.buildModelFromUrdf('cartpole.txt')
pnc_data = pnc_model.createData()

q = np.zeros((2, 1))
v = np.zeros((2, 1))
for _ in range(10000000):
    pnc.forwardKinematics(pnc_model, pnc_data, q, v)
```

```
valgrind --tool=massif python test.py
```

![Screenshot from 2020-02-19 16-17-18](https://user-images.githubusercontent.com/17752950/74850937-d8479580-533a-11ea-9f22-ad4d3ff074d3.png)

[cartpole.txt](https://github.com/stack-of-tasks/eigenpy/files/4225967/cartpole.txt)

I hope it is possible to fix it.

Best

**Comment by jcarpent** [comment]
@duburcqa I checked on my side and with eigenpy 2.0.2, I don't have any leack. Which version of EigenPy are you using?

**Comment by duburcqa** [comment]
I'm using Python3.6, Eigenpy 2.0.2 and Pinocchio 2.2.2 (both installed using `sudo apt install robotpkg-py36-pinocchio robotpkg-py36-eigenpy`)

**Comment by jcarpent** [comment]
@duburcqa Could check PR #158?

**Comment by jcarpent** [comment]
fixed by #158.

**Comment by duburcqa** [comment]
I will have a look as soon as possible, probably tomorrow morning. Thanks !

**Comment by jcarpent** [comment]
@duburcqa Any news?

**Comment by duburcqa** [comment]
@jcarpent Sorry for the delay, I wasn't able to build pinocchio from source before now. I have tested the same script on Ubuntu 18 with eigenpy 2.3.1 and pinocchio 2.4.2 and the issue is still there :/ This issue should be reopened.

**Comment by jcarpent** [comment]
I've tried on my side and I don't have it. Could you please provide a Docker file with all the required content?

**Comment by jcarpent** [comment]
Could you also provide the full details of your screenshot and the resulting Valgrind output? Otherwise, it is hard to start the debug phase!

**Comment by jcarpent** [comment]
The leak is not coming from EigenPy but from Pinocchio. The destroyer of Eigen::MatrixBase<> is properly called. Including `eigenpy.hpp` in all the files of the Pinocchio bindings should solve the issue!

**Comment by duburcqa** [comment]
Here is the build script I use https://github.com/Wandercraft/jiminy/blob/master/build_tools/build_install_deps_linux.sh

**Comment by duburcqa** [comment]
> Including eigenpy.hpp in all the files of the Pinocchio bindings should solve the issue!

I didn't modified the source of eigenpy and pinocchio.

**Comment by jcarpent** [comment]
Did you read my previous comments?
The issue is not coming from EigenPy but rather the way Boost.Python is handling the memory. The fix for Pinocchio is here: https://github.com/stack-of-tasks/pinocchio/pull/1168

**Comment by jcarpent** [comment]
@duburcqa Could you try on your side and confirm the fix?

**Comment by duburcqa** [comment]
@jcarpent Unfortunately, the result is the same :/

Find attached the massif result:
[massif.out.8899.txt](https://github.com/stack-of-tasks/eigenpy/files/4508171/massif.out.8899.txt)

**Comment by jcarpent** [comment]
I've checked on my side, and there is no more leak issue on 18.04. I've checked with memcheck.
Which version of Pinocchio have you tried? Again, providing a container will help us a lot. The script you provided does not work on my side.

**Comment by duburcqa** [comment]
Yes it's working fine !

**Comment by jcarpent** [comment]
Do you change your mind? Or what happens within the last 5min?

**Comment by duburcqa** [comment]
I tried on a corrupted setup, it was loading the old dynamic library of pinocchio instead of the patched one x)
